- name: Setup base hpc
  hosts: all
  gather_facts: true
  tasks:
  - name: Install lshw
    become: yes
    yum:
      name: lshw

  - name: Benchmark MPI
    become: yes
    become_user: hpc
    run_once: true
    shell: |
      source /opt/intel/impi/5.1.3.223/bin64/mpivars.sh  
      export I_MPI_FABRICS=tcp
      export I_MPI_DAPL_PROVIDER=ofa-v2-ib0
      export I_MPI_DYNAMIC_CONNECTION=0
      sudo mkdir /mnt/benchmark
      sudo chmod 777 /mnt/benchmark
      
      echo `uname -a` > /mnt/benchmark/info.txt
      echo I_MPI_FABRICS=$I_MPI_FABRICS >> /mnt/benchmark/info.txt
      echo I_MPI_DAPL_PROVIDER=$I_MPI_DAPL_PROVIDER >> /mnt/benchmark/info.txt
      mpirun --version >> /mnt/benchmark/info.txt
      
      sudo lshw > /mnt/benchmark/lshw.txt
      
      mpirun -hosts {{ groups['all'] | map('extract', hostvars, ['ansible_eth0', 'ipv4', 'address']) | join(',') }} IMB-MPI1 > /mnt/benchmark/stdout.txt 2> /mnt/benchmark/stderr.txt
      
      azcopy copy /mnt/benchmark \"{{ lookup('env','SAS_URL') }}\" --recursive
