- name: Setup base hpc
  hosts: all
  gather_facts: true
  tasks:
  - name: Install lshw
    become: yes
    yum:
      name: lshw

  - name: DPDK Configure
    become: yes
    shell: |
      sudo dracut --add-drivers "mlx4_en mlx4_ib mlx5_ib" -f
      sudo yum install -y gcc kernel-devel-`uname -r` numactl-devel.x86_64 librdmacm-devel libmnl-devel

  - name: DPDK Files
    become: yes
    unarchive:
      src: https://fast.dpdk.org/rel/dpdk-18.05.1.tar.xz
      remote_src: yes
  
  - name: Compile DPDK
    become: yes
    shell: |
      cd dpdk-stable-18.05.1
      make config T=x86_64-native-linuxapp-gcc
      sed -ri 's,(MLX._PMD=)n,\1y,' build/.config
      make -j
      sudo make install
      
  - name: Reboot to enable DPDK module
    reboot:

  - name: DPDK Config
    become: yes
    shell: |
      echo 1024 | sudo tee /sys/devices/system/node/node*/hugepages/hugepages-2048kB/nr_hugepages  
      mkdir /mnt/huge
      mount -t hugetlbfs nodev /mnt/huge