- name: Setup base hpc
  hosts: all
  become: yes
  tasks:
  - name: Make sure epel-release is available
    yum:
      name: epel-release

  - name: Install packages for compilation
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - cmake
      - git
      - makedepf90
      - gcc
      - netcdf
      - netcdf-devel
      - netcdf-fortran-devel
      - netcdf-fortran
      - netcdf-static
      - mpich-3.0
      - mpich-3.0-devel
      - netcdf-fortran-mpich
      - netcdf-fortran-mpich-devel
      - hdf5-mpich
      - hdf5-mpich-devel

  - name: Add user hpc
    user:
      name: hpc
      shell: /bin/bash

  - name: Set SSH key
    authorized_key:
      user: hpc
      state: present
      key: "{{ lookup('file', '~/hpc.key.pub') }}"

  - name: Add hpc to sudoers
    copy:
      dest: "/etc/sudoers.d/devops"
      content: "hpc  ALL=(ALL)  NOPASSWD: ALL"

  - name: Install azcopy to /usr/bin
    become: yes
    unarchive:
      src: https://aka.ms/downloadazcopy-v10-linux
      dest: /usr/bin
      remote_src: yes
      extra_opts: [--strip-components=1]