- name: Setup base hpc
  hosts: all
  tasks:
  - name: Make sure epel-release is available
    become: yes
    yum:
      name: epel-release

  - name: Install packages for compilation
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - cmake
      - git
      - makedepf90
      - gcc
      - netcdf
      - netcdf-devel
      - netcdf-fortran-devel
      - netcdf-fortran
      - netcdf-static
      - mpich-3.0
      - mpich-3.0-devel
      - netcdf-fortran-mpich
      - netcdf-fortran-mpich-devel
      - hdf5-mpich
      - hdf5-mpich-devel
